# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public%app.path.media_images%'
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public%app.path.media_images%'
    filter_sets:
        name:
            jpeg_quality: 80
        # the name of the "filter set"
        thumb_widen:
            data_loader: default
            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:
                relative_resize:
                    widen: 100
