vich_uploader:
    db_driver: orm
    mappings:
       media_images:
           uri_prefix: '%app.path.media_images%'
           upload_destination: '%kernel.project_dir%/public%app.path.media_images%'
