easy_admin:
    entities:
        Page:
            class: App\Entity\Page
            label: 'Pages'
            list:
                title: 'Liste des pages'
                fields: 
                    - id
                    - { property: 'title', label: 'Titre' }
                    - { property: 'position', label: 'Position' }
                    - { property: 'enabled', label: 'Active' }
                search:
                    fields: ['page.title', 'page.description']
            form:
                fields:
                    - { type: 'group', columns: 12, label: 'Informations' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'description', label: 'Description', type: 'text_editor'}
                    - { property: 'cta', label: 'Lien du call to action' }
                    - { property: 'ctaLabel', label: 'Label du call to action' }
                    - { property: 'enabled', label: 'Active'}
                    - { type: 'group', columns: 6, label: 'SEO' }
                    - { property: 'metaTitle', label: 'Méta titre'}
                    - { property: 'metaDescription', label: 'Méta description'}
                    - { property: 'slug', label: 'Slug', type_options: { required: false } }
                    - { type: 'group', columns: 6, label: 'Associations' }
                    - { property: 'family', label: 'Famille associée'}
                    - { property: 'worksheet', label: 'Fiche travaux associée'}
                    - { property: 'aid', label: 'Aide associée'}
