easy_admin:
    entities:
        Page:
            class: App\Entity\Page
            label: 'Pages'
            list:
                title: 'Liste des pages'
                fields: 
                    - id
                    - { property: 'title', label: 'Titre' }
                    - { property: 'position', label: 'Position' }
                    - { property: 'enabled', label: 'Active', type: 'boolean' }
                search:
                    fields: ['page.title', 'page.description']
            form:
                fields:
                    - { type: 'group', columns: 6, label: 'Informations' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'description', label: 'Description', type: 'fos_ckeditor'}
                    - { property: 'position', label: 'Position', type: 'integer'}
                    - { type: 'group', columns: 6, label: 'SEO' }
                    - { property: 'meta_title', label: 'Méta titre'}
                    - { property: 'meta_description', label: 'Méta description'}
                    - { property: 'slug', label: 'Slug' }
                    - { type: 'group', columns: 6, label: 'Associations' }
                    - { property: 'family', label: 'Famille associée'}
                    - { property: 'worksheet', label: 'Fiche travaux associée'}
