easy_admin:
    site_name : 'Backoffice OLMI' 
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:    
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'
        assets:
            css:
                - 'admin/css/dragndrop.css'
            js:
                - 'admin/js/dragndrop.js'
