easy_admin:
    design:
        menu:
        - { label: 'Dashboard', route: 'admin_dashboard', icon: 'dashboard' }
        - { label: 'Référentiel' }
        - { label: 'Utilisateurs', entity: 'User', icon: 'users', permission: 'ROLE_SUPER_ADMIN' }
        - { label: 'Clients', entity: 'Client', icon: 'users', permission: 'ROLE_ADMIN' }
        - { label: 'CMS' }
        - { label: 'Pages', entity: 'Page', icon: 'files-o', permission: 'ROLE_EDITOR' }
        - { label: 'Blocks', entity: 'PageBlock', icon: 'columns', permission: 'ROLE_EDITOR' }
        - { label: 'Médias', entity: 'Media', icon: 'picture-o', permission: 'ROLE_EDITOR' }
        - { label: 'Divers' }
        - { label: 'Familles', entity: 'Family', icon: 'files-o', permission: 'ROLE_EDITOR' }
        - { label: 'Fiche travaux', entity: 'Worksheet', icon: 'files-o', permission: 'ROLE_EDITOR' }
        - { label: 'Aides', entity: 'Aid', icon: 'files-o', permission: 'ROLE_EDITOR' }
        - { label: 'Frontend' }
        - { label: 'Accueil', route: 'homepage', icon: 'home' }

        
